version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=inventaireG2
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=p4ssw0rd
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=inventaireG2
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=p4ssw0rd
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data: